
<footer>
	<ul class="f2">
		<li class="f3">Booksmore
			<ul class="f5">
				<li>Home</li>
				<li>About Us</li>
				<li>Careers</li>
				<li>Blog</li>
				<li>Press</li>
				</ul>
			</li>
		<li class="f3">Order
			<ul class="f5">
				<li>Discounts</li>
				<li>Request a book</li>
				<li>Educational Bargains</li>
				<li>Cancellation & Returns</li>
				</ul>
			</li>
		<li class="f3"> Orders & Shipping
			<ul class="f5">
				<li>Free Shipping</li>
				<li>Shipping Coverage</li>
				<li>Transit Policies</li>
				<li>FAQs</li>
				</ul>
			</li>
		<li class="f3">Quick Help
			<ul class="f5">
				<li>Customer Service</li>
				<li>Sitemap</li>
				<li>Accessibility</li>
				<li>FAQs</li>
				</ul>
			</li>
		<li class="f3">We are Here
			<ul class="f5">
				<li>Booksmore Inc.,</li>
				<li>Allahabad 211007, U.P, India.</li>
				<li>Ph. +91 4212122,</li>
				<li>e-mail: support@bookshore.in</li>
				</ul>
			</li>

		</ul>
	</div>
		<div class="f6"><span>Terms of use |</span><span> Return policy |</span><span> Privacy policy |</span><span> Copyrights</span><span id="feedback" class="fb2">Send Feedback</span> | © Booksmore Inc. 2012 </div>
	</footer>
	</section>
</body>
</html>
