<section id="container">
	<section id="showcase" class="super-panels">
		<div class="panel panel_e"> Either the Username or Password is incorrect.</div>
		<div class="panel">
		<div class="userpanel">
		<form action="login.php" method="post">
		<ul>
		<li><label for="username">Username</label><input type="text" name="username" placeholder="username" title="Enter your username." required/></li>
		<li><label for="password">Password</label><input type="password" name="password" placeholder="password" title="Enter your username." required/></li>
		<li><label for="persistent">Remember Me</label><input type="checkbox" name="persistent" title="Check if you trust this computer or mobile."/></li>
		<li><input type="submit" value="Sign In" /></li>
		</ul>
		</form>
		</div>
		</div>
		</section>
</section>